version: '3'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - mongo
    environment:
      - MONGO_HOST=mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"